export type Question = {
  id: string;
  set?: "storage" | "civil-law";
  category: string;
  prompt: string;
  choices: string[];
  correctChoice: string;
  explanation: string;
  source?: string;
  sourceUrl?: string;
  importance?: 1 | 2 | 3;
  tags?: string[];
};

const storagePeriodSource = "不動産登記規則第28条（2026年8月6日確認）";

export const questions: Question[] = [
  {
    id: "storage-registration-record",
    category: "保存期間",
    prompt: "閉鎖されていない登記記録の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation: "閉鎖登記記録を除く登記記録は、永久に保存される。",
    source: storagePeriodSource,
    tags: ["登記記録"],
  },
  {
    id: "storage-closed-land-record",
    category: "保存期間",
    prompt: "土地に関する閉鎖登記記録の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "50年",
    explanation: "土地に関する閉鎖登記記録は、閉鎖した日から50年間保存される。",
    source: storagePeriodSource,
    tags: ["閉鎖登記記録", "土地"],
  },
  {
    id: "storage-closed-building-record",
    category: "保存期間",
    prompt: "建物に関する閉鎖登記記録の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation: "建物に関する閉鎖登記記録は、閉鎖した日から30年間保存される。",
    source: storagePeriodSource,
    tags: ["閉鎖登記記録", "建物"],
  },
  {
    id: "storage-map",
    category: "保存期間",
    prompt: "地図（閉鎖したものを含む）の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation: "地図は、閉鎖したものも含めて永久に保存される。",
    source: storagePeriodSource,
    tags: ["地図", "閉鎖地図"],
  },
  {
    id: "storage-map-equivalent-drawing",
    category: "保存期間",
    prompt: "地図に準ずる図面（閉鎖したものを含む）の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation: "地図に準ずる図面は、閉鎖したものも含めて永久に保存される。",
    source: storagePeriodSource,
    tags: ["地図に準ずる図面", "閉鎖図面"],
  },
  {
    id: "storage-building-location-map",
    category: "保存期間",
    prompt: "建物所在図（閉鎖したものを含む）の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation: "建物所在図は、閉鎖したものも含めて永久に保存される。",
    source: storagePeriodSource,
    tags: ["建物所在図", "閉鎖建物所在図"],
  },
  {
    id: "storage-land-building-drawings",
    category: "保存期間",
    prompt:
      "申請書類つづり込み帳につづり込まれたものを除く、土地所在図・地積測量図・建物図面・各階平面図の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation:
      "土地所在図、地積測量図、建物図面及び各階平面図は、申請書類つづり込み帳につづり込まれたものを除き、永久に保存される。",
    source: storagePeriodSource,
    tags: ["土地所在図", "地積測量図", "建物図面", "各階平面図"],
  },
  {
    id: "storage-closed-land-building-drawings",
    category: "保存期間",
    prompt:
      "閉鎖した土地所在図・地積測量図・建物図面・各階平面図の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation:
      "これらの閉鎖した図面は、閉鎖した日から30年間保存される。申請書類つづり込み帳につづり込まれたものは別の起算点による。",
    source: storagePeriodSource,
    tags: ["閉鎖図面", "土地所在図", "地積測量図", "建物図面", "各階平面図"],
  },
  {
    id: "storage-filed-drawings",
    category: "保存期間",
    prompt:
      "申請書類つづり込み帳につづり込まれた土地所在図・地積測量図・建物図面・各階平面図・地役権図面の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation:
      "これらの図面は、電磁的記録に記録して保存した日から30年間保存される。",
    source: storagePeriodSource,
    tags: ["申請書類つづり込み帳", "土地所在図", "地積測量図", "建物図面", "各階平面図", "地役権図面"],
  },
  {
    id: "storage-description-application-information",
    category: "保存期間",
    prompt: "表示に関する登記の申請情報及び添付情報（図面を除く）の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation:
      "表示に関する登記の申請情報及び添付情報は、受付の日から30年間保存される。図面には保存方法に応じた別の起算点がある。",
    source: storagePeriodSource,
    tags: ["表示に関する登記", "申請情報", "添付情報"],
  },
  {
    id: "storage-ex-officio-description-documents",
    category: "保存期間",
    prompt: "職権表示登記等書類つづり込み帳につづり込まれた書類の情報の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation: "職権表示登記等の書類に記載された情報は、立件の日から30年間保存される。",
    source: storagePeriodSource,
    tags: ["職権表示登記", "職権表示登記等書類つづり込み帳"],
  },
  {
    id: "storage-joint-collateral-list",
    category: "保存期間",
    prompt: "共同担保目録の保存期間は？",
    choices: ["永久", "30年", "20年", "10年", "5年"],
    correctChoice: "10年",
    explanation: "共同担保目録は、全ての事項を抹消した日から10年間保存される。",
    source: storagePeriodSource,
    tags: ["共同担保目録"],
  },
  {
    id: "storage-trust-register",
    category: "保存期間",
    prompt: "信託目録の保存期間は？",
    choices: ["永久", "30年", "20年", "10年", "5年"],
    correctChoice: "20年",
    explanation: "信託目録は、信託の登記を抹消した日から20年間保存される。",
    source: storagePeriodSource,
    tags: ["信託目録"],
  },
  {
    id: "storage-reception-book",
    category: "保存期間",
    prompt: "受付帳に記録された情報の保存期間は？",
    choices: ["永久", "30年", "20年", "10年", "1年"],
    correctChoice: "10年",
    explanation:
      "受付帳に記録された情報は、受付の年の翌年から10年間保存される。ただし、登記識別情報に関する証明の請求に係る受付帳は別である。",
    source: storagePeriodSource,
    tags: ["受付帳"],
  },
  {
    id: "storage-registration-identification-certificate-reception-book",
    category: "保存期間",
    prompt: "登記識別情報に関する証明の請求に係る受付帳の情報の保存期間は？",
    choices: ["永久", "10年", "5年", "3年", "1年"],
    correctChoice: "1年",
    explanation:
      "登記識別情報に関する証明の請求に係る受付帳の情報は、受付の年の翌年から1年間保存される。",
    source: storagePeriodSource,
    tags: ["受付帳", "登記識別情報", "証明の請求"],
  },
  {
    id: "storage-registration-identification-invalidation-request",
    category: "保存期間",
    prompt: "登記識別情報の失効の申出に関する情報の保存期間は？",
    choices: ["永久", "30年", "20年", "10年", "5年"],
    correctChoice: "10年",
    explanation: "登記識別情報の失効の申出に関する情報は、申出の受付の日から10年間保存される。",
    source: storagePeriodSource,
    tags: ["登記識別情報", "失効の申出"],
  },
  {
    id: "storage-request-documents",
    category: "保存期間",
    prompt:
      "登記事項証明書の交付請求書など、請求書類つづり込み帳の書類に記載された情報の保存期間は？",
    choices: ["永久", "10年", "5年", "3年", "1年"],
    correctChoice: "1年",
    explanation: "請求書類つづり込み帳の書類に記載された情報は、受付の日から1年間保存される。",
    source: storagePeriodSource,
    tags: ["登記事項証明書", "交付請求", "請求書類つづり込み帳"],
  },
];

const civilCodeUrl = "https://laws.e-gov.go.jp/law/129AC0000000089";
const landAndHouseLeaseActUrl = "https://laws.e-gov.go.jp/law/403AC0000000090";
const confirmedAt = "2026年8月13日確認";

const civilLawQuestions: Question[] = [
  {
    id: "civil-absence-ordinary",
    set: "civil-law",
    category: "民法・総則",
    prompt: "普通失踪で、失踪宣告の要件となる生死不明の期間は？",
    choices: ["1年", "3年", "5年", "7年", "10年"],
    correctChoice: "7年",
    explanation: "不在者の生死が7年間明らかでないとき、家庭裁判所は利害関係人の請求により失踪の宣告をすることができる。",
    source: `民法第30条第1項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["失踪宣告", "普通失踪"],
  },
  {
    id: "civil-absence-special",
    set: "civil-law",
    category: "民法・総則",
    prompt: "特別失踪で、危難が去った後に生死不明が続く必要期間は？",
    choices: ["6か月", "1年", "3年", "5年", "7年"],
    correctChoice: "1年",
    explanation: "戦争・船舶の沈没その他の危難が去った後、1年間生死が明らかでないことが要件となる。死亡したものとみなされる時点は、危難が去った時である。",
    source: `民法第30条第2項・第31条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["失踪宣告", "特別失踪"],
  },
  {
    id: "civil-rescission-subjective",
    set: "civil-law",
    category: "民法・総則",
    prompt: "取消権は、追認できる時から何年間行使しないと時効で消滅する？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "取消権は、追認をすることができる時から5年間行使しないと、時効によって消滅する。",
    source: `民法第126条前段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["取消権", "消滅時効"],
  },
  {
    id: "civil-rescission-objective",
    set: "civil-law",
    category: "民法・総則",
    prompt: "取消権は、行為の時から何年を経過すると消滅する？",
    choices: ["5年", "10年", "15年", "20年", "30年"],
    correctChoice: "20年",
    explanation: "追認できる時からの5年とは別に、行為の時から20年を経過したときも取消権は消滅する。",
    source: `民法第126条後段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["取消権", "消滅時効"],
  },
  {
    id: "civil-acquisitive-prescription-good-faith",
    set: "civil-law",
    category: "民法・物権",
    prompt: "所有の意思をもって平穏・公然に占有し、占有開始時に善意無過失だった場合、所有権の取得時効期間は？",
    choices: ["5年", "7年", "10年", "15年", "20年"],
    correctChoice: "10年",
    explanation: "占有開始時に善意かつ無過失であれば、10年間の占有で所有権を時効取得する。",
    source: `民法第162条第2項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["取得時効", "善意無過失"],
  },
  {
    id: "civil-acquisitive-prescription-general",
    set: "civil-law",
    category: "民法・物権",
    prompt: "善意無過失の短期取得時効が成立しない場合、所有権の取得時効期間は？",
    choices: ["5年", "10年", "15年", "20年", "30年"],
    correctChoice: "20年",
    explanation: "所有の意思をもって平穏・公然に他人の物を20年間占有すると、所有権を取得する。",
    source: `民法第162条第1項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["取得時効"],
  },
  {
    id: "civil-lease-maximum",
    set: "civil-law",
    category: "民法・契約",
    prompt: "民法上の賃貸借について、1回に定められる存続期間の上限は？",
    choices: ["10年", "20年", "30年", "50年", "上限なし"],
    correctChoice: "50年",
    explanation: "賃貸借の存続期間は50年を超えられない。更新はできるが、更新後の期間も更新時から50年を超えられない。",
    source: `民法第604条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["賃貸借", "存続期間"],
  },
  {
    id: "civil-land-lease-minimum",
    set: "civil-law",
    category: "民法・契約",
    prompt: "借地借家法上の普通借地権について、当初の存続期間は原則何年？",
    choices: ["10年", "20年", "30年", "50年", "上限なし"],
    correctChoice: "30年",
    explanation: "普通借地権の当初の存続期間は30年。契約で30年より長い期間を定めたときは、その期間となる。",
    source: `借地借家法第3条（${confirmedAt}）`,
    sourceUrl: landAndHouseLeaseActUrl,
    importance: 1,
    tags: ["借地権", "存続期間"],
  },
  {
    id: "civil-superficies-ground-rent-default",
    set: "civil-law",
    category: "民法・物権",
    prompt: "定期の地代を支払う地上権者が、何年以上続けて地代を支払わないと、土地所有者は地上権の消滅を請求できる？",
    choices: ["1年以上", "2年以上", "3年以上", "5年以上", "10年以上"],
    correctChoice: "2年以上",
    explanation: "地上権の地代には永小作権の規定が準用され、引き続き2年以上支払を怠ると、土地所有者は消滅を請求できる。",
    source: `民法第266条第1項・第276条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["地上権", "地代", "消滅請求"],
  },
  {
    id: "civil-easement-extinctive-prescription",
    set: "civil-law",
    category: "民法・物権",
    prompt: "地役権の消滅時効期間は？",
    choices: ["5年", "10年", "15年", "20年", "30年"],
    correctChoice: "20年",
    explanation: "地役権は所有権以外の財産権として20年で時効消滅する。起算点は、非継続地役権では最後の行使時、継続地役権では行使を妨げる事実が生じた時である。",
    source: `民法第166条第2項・第291条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["地役権", "消滅時効"],
  },
  {
    id: "civil-immovable-pledge-duration",
    set: "civil-law",
    category: "民法・物権",
    prompt: "不動産質権の1回の存続期間の上限は？",
    choices: ["5年", "10年", "20年", "30年", "50年"],
    correctChoice: "10年",
    explanation: "不動産質権の存続期間は10年を超えられない。更新できるが、更新後も更新時から10年が上限となる。",
    source: `民法第360条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["不動産質権", "存続期間"],
  },
  {
    id: "civil-prescription-court-claim",
    set: "civil-law",
    category: "民法・時効",
    prompt: "裁判上の請求が、権利を確定させずに終了した場合、その終了時から時効完成が猶予される期間は？",
    choices: ["3か月", "6か月", "1年", "3年", "5年"],
    correctChoice: "6か月",
    explanation: "裁判上の請求などが権利を確定させずに終了した場合、終了時から6か月を経過するまで時効は完成しない。",
    source: `民法第147条第1項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["時効完成猶予", "裁判上の請求"],
  },
  {
    id: "civil-prescription-provisional-seizure",
    set: "civil-law",
    category: "民法・時効",
    prompt: "仮差押え・仮処分の事由が終了した後、時効完成が猶予される期間は？",
    choices: ["3か月", "6か月", "1年", "3年", "5年"],
    correctChoice: "6か月",
    explanation: "仮差押えまたは仮処分の事由が終了した時から6か月を経過するまで、時効は完成しない。",
    source: `民法第149条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["時効完成猶予", "仮差押え", "仮処分"],
  },
  {
    id: "civil-prescription-demand",
    set: "civil-law",
    category: "民法・時効",
    prompt: "催告があった時から、時効完成が猶予される期間は？",
    choices: ["3か月", "6か月", "1年", "3年", "5年"],
    correctChoice: "6か月",
    explanation: "催告時から6か月を経過するまで時効は完成しない。この猶予中に再度催告しても、完成猶予の効力はない。",
    source: `民法第150条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["時効完成猶予", "催告"],
  },
  {
    id: "civil-claim-prescription-subjective",
    set: "civil-law",
    category: "民法・時効",
    prompt: "債権者が権利を行使できることを知った時から、債権の消滅時効期間は？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "債権者が権利を行使できることを知った時から5年間行使しないと、債権は時効によって消滅する。",
    source: `民法第166条第1項第1号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["債権", "消滅時効"],
  },
  {
    id: "civil-claim-prescription-objective",
    set: "civil-law",
    category: "民法・時効",
    prompt: "権利を行使できる時から、債権の消滅時効期間は？",
    choices: ["3年", "5年", "10年", "20年", "30年"],
    correctChoice: "10年",
    explanation: "権利を行使できる時から10年間行使しないと、債権は時効によって消滅する。知った時からの5年と、先に満了する方で完成する。",
    source: `民法第166条第1項第2号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["債権", "消滅時効"],
  },
  {
    id: "civil-inheritance-recovery-subjective",
    set: "civil-law",
    category: "民法・相続",
    prompt: "相続権を侵害された事実を知った時から、相続回復請求権の消滅時効期間は？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "相続人または法定代理人が相続権を侵害された事実を知った時から5年間行使しないと、時効で消滅する。",
    source: `民法第884条前段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["相続回復請求権", "消滅時効"],
  },
  {
    id: "civil-inheritance-recovery-objective",
    set: "civil-law",
    category: "民法・相続",
    prompt: "相続開始の時から、相続回復請求権が消滅するまでの期間は？",
    choices: ["5年", "10年", "15年", "20年", "30年"],
    correctChoice: "20年",
    explanation: "相続開始の時から20年を経過したときも、相続回復請求権は消滅する。",
    source: `民法第884条後段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["相続回復請求権"],
  },
  {
    id: "civil-legitime-subjective",
    set: "civil-law",
    category: "民法・相続",
    prompt: "相続開始と遺留分を侵害する贈与・遺贈を知った時から、遺留分侵害額請求権の消滅時効期間は？",
    choices: ["6か月", "1年", "3年", "5年", "10年"],
    correctChoice: "1年",
    explanation: "相続開始と遺留分侵害の贈与・遺贈を知った時から1年間行使しないと、時効で消滅する。",
    source: `民法第1048条前段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["遺留分侵害額請求権", "消滅時効"],
  },
  {
    id: "civil-legitime-objective",
    set: "civil-law",
    category: "民法・相続",
    prompt: "相続開始の時から、遺留分侵害額請求権が消滅するまでの期間は？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "10年",
    explanation: "相続開始の時から10年を経過したときも、遺留分侵害額請求権は消滅する。",
    source: `民法第1048条後段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["遺留分侵害額請求権"],
  },
  {
    id: "civil-repurchase-maximum",
    set: "civil-law",
    category: "民法・契約",
    prompt: "買戻しの期間として特約で定められる上限は？",
    choices: ["3年", "5年", "10年", "20年", "50年"],
    correctChoice: "10年",
    explanation: "買戻しの期間は10年を超えられず、これより長く定めても10年となる。いったん定めた期間は後から伸長できない。",
    source: `民法第580条第1項・第2項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["買戻し", "買戻特約"],
  },
  {
    id: "civil-repurchase-unspecified",
    set: "civil-law",
    category: "民法・契約",
    prompt: "買戻しについて期間を定めなかった場合、何年以内に買戻しをしなければならない？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "買戻しについて期間を定めなかったときは、5年以内に買戻しをしなければならない。",
    source: `民法第580条第3項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["買戻し", "買戻特約"],
  },
  {
    id: "civil-short-lease-forest",
    set: "civil-law",
    category: "民法・契約",
    prompt: "処分権限のない者がする、樹木の栽植・伐採を目的とする山林の短期賃貸借の上限は？",
    choices: ["3年", "5年", "10年", "20年", "50年"],
    correctChoice: "10年",
    explanation: "処分権限のない者による山林の賃貸借は10年を超えられない。",
    source: `民法第602条第1号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["短期賃貸借", "山林"],
  },
  {
    id: "civil-short-lease-land",
    set: "civil-law",
    category: "民法・契約",
    prompt: "処分権限のない者がする、山林以外の土地の短期賃貸借の上限は？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "樹木の栽植・伐採を目的とする山林以外の土地の賃貸借は、5年を超えられない。",
    source: `民法第602条第2号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["短期賃貸借", "土地"],
  },
  {
    id: "civil-short-lease-building",
    set: "civil-law",
    category: "民法・契約",
    prompt: "処分権限のない者がする、建物の短期賃貸借の上限は？",
    choices: ["1年", "2年", "3年", "5年", "10年"],
    correctChoice: "3年",
    explanation: "処分権限のない者による建物の賃貸借は、3年を超えられない。",
    source: `民法第602条第3号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["短期賃貸借", "建物"],
  },
  {
    id: "civil-short-lease-movables",
    set: "civil-law",
    category: "民法・契約",
    prompt: "処分権限のない者がする、動産の短期賃貸借の上限は？",
    choices: ["3か月", "6か月", "1年", "3年", "5年"],
    correctChoice: "6か月",
    explanation: "処分権限のない者による動産の賃貸借は、6か月を超えられない。",
    source: `民法第602条第4号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["短期賃貸借", "動産"],
  },
  {
    id: "civil-inheritance-deliberation",
    set: "civil-law",
    category: "民法・相続",
    prompt: "相続人が自己のために相続開始があったことを知った時から、承認・放棄を決める熟慮期間は？",
    choices: ["1か月", "3か月", "6か月", "1年", "3年"],
    correctChoice: "3か月",
    explanation: "原則として3か月以内に単純承認・限定承認または放棄をしなければならない。家庭裁判所は請求により期間を伸長できる。",
    source: `民法第915条第1項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["相続の承認", "相続放棄", "熟慮期間"],
  },
];

questions.push(...civilLawQuestions);
