export type QuestionSet =
  | "storage"
  | "real-estate-registration"
  | "boundary-determination"
  | "surveyor-law"
  | "civil-law";

export type Question = {
  id: string;
  /** 省略時は、従来どおり保存期間モードに属する。 */
  sets?: QuestionSet[];
  category: string;
  prompt: string;
  choices: string[];
  correctChoice: string;
  explanation: string;
  source?: string;
  sourceUrl?: string;
  importance?: 1 | 2 | 3;
  tags?: string[];
};

const storagePeriodSource = "不動産登記規則第28条（2026年8月6日確認）";
const realEstateRegistrationActUrl = "https://laws.e-gov.go.jp/law/416AC0000000123";
const realEstateRegistrationOrderUrl = "https://laws.e-gov.go.jp/law/416CO0000000379";
const realEstateRegistrationRulesUrl = "https://laws.e-gov.go.jp/law/417M60000010018";
const registrationAndLicenseTaxActUrl = "https://laws.e-gov.go.jp/law/342AC0000000035";
const surveyorActUrl = "https://laws.e-gov.go.jp/law/325AC1000000228";
const surveyorRulesUrl = "https://laws.e-gov.go.jp/law/354M50000010053";
const addressChangeRegistrationGuideUrl = "https://www.moj.go.jp/MINJI/minji05_00693.html";
const realEstateRegistrationConfirmedAt = "2026年8月23日確認";
const realEstateRegistrationDeadlinesConfirmedAt = "2026年8月28日確認";

export const questions: Question[] = [
  {
    id: "storage-registration-record",
    category: "保存期間",
    prompt: "閉鎖されていない登記記録の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation: "閉鎖登記記録を除く登記記録は、永久に保存される。",
    source: storagePeriodSource,
    tags: ["登記記録"],
  },
  {
    id: "storage-closed-land-record",
    category: "保存期間",
    prompt: "土地に関する閉鎖登記記録の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "50年",
    explanation: "土地に関する閉鎖登記記録は、閉鎖した日から50年間保存される。",
    source: storagePeriodSource,
    tags: ["閉鎖登記記録", "土地"],
  },
  {
    id: "storage-closed-building-record",
    category: "保存期間",
    prompt: "建物に関する閉鎖登記記録の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation: "建物に関する閉鎖登記記録は、閉鎖した日から30年間保存される。",
    source: storagePeriodSource,
    tags: ["閉鎖登記記録", "建物"],
  },
  {
    id: "storage-map",
    category: "保存期間",
    prompt: "地図（閉鎖したものを含む）の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation: "地図は、閉鎖したものも含めて永久に保存される。",
    source: storagePeriodSource,
    tags: ["地図", "閉鎖地図"],
  },
  {
    id: "storage-map-equivalent-drawing",
    category: "保存期間",
    prompt: "地図に準ずる図面（閉鎖したものを含む）の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation: "地図に準ずる図面は、閉鎖したものも含めて永久に保存される。",
    source: storagePeriodSource,
    tags: ["地図に準ずる図面", "閉鎖図面"],
  },
  {
    id: "storage-building-location-map",
    category: "保存期間",
    prompt: "建物所在図（閉鎖したものを含む）の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation: "建物所在図は、閉鎖したものも含めて永久に保存される。",
    source: storagePeriodSource,
    tags: ["建物所在図", "閉鎖建物所在図"],
  },
  {
    id: "storage-land-building-drawings",
    category: "保存期間",
    prompt:
      "申請書類つづり込み帳につづり込まれたものを除く、土地所在図・地積測量図・建物図面・各階平面図の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "永久",
    explanation:
      "土地所在図、地積測量図、建物図面及び各階平面図は、申請書類つづり込み帳につづり込まれたものを除き、永久に保存される。",
    source: storagePeriodSource,
    tags: ["土地所在図", "地積測量図", "建物図面", "各階平面図"],
  },
  {
    id: "storage-closed-land-building-drawings",
    category: "保存期間",
    prompt:
      "閉鎖した土地所在図・地積測量図・建物図面・各階平面図の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation:
      "これらの閉鎖した図面は、閉鎖した日から30年間保存される。申請書類つづり込み帳につづり込まれたものは別の起算点による。",
    source: storagePeriodSource,
    tags: ["閉鎖図面", "土地所在図", "地積測量図", "建物図面", "各階平面図"],
  },
  {
    id: "storage-filed-drawings",
    category: "保存期間",
    prompt:
      "申請書類つづり込み帳につづり込まれた土地所在図・地積測量図・建物図面・各階平面図・地役権図面の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation:
      "これらの図面は、電磁的記録に記録して保存した日から30年間保存される。",
    source: storagePeriodSource,
    tags: ["申請書類つづり込み帳", "土地所在図", "地積測量図", "建物図面", "各階平面図", "地役権図面"],
  },
  {
    id: "storage-description-application-information",
    category: "保存期間",
    prompt: "表示に関する登記の申請情報及び添付情報（図面を除く）の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation:
      "表示に関する登記の申請情報及び添付情報は、受付の日から30年間保存される。図面には保存方法に応じた別の起算点がある。",
    source: storagePeriodSource,
    tags: ["表示に関する登記", "申請情報", "添付情報"],
  },
  {
    id: "storage-ex-officio-description-documents",
    category: "保存期間",
    prompt: "職権表示登記等書類つづり込み帳につづり込まれた書類の情報の保存期間は？",
    choices: ["永久", "50年", "30年", "20年", "10年"],
    correctChoice: "30年",
    explanation: "職権表示登記等の書類に記載された情報は、立件の日から30年間保存される。",
    source: storagePeriodSource,
    tags: ["職権表示登記", "職権表示登記等書類つづり込み帳"],
  },
  {
    id: "storage-joint-collateral-list",
    category: "保存期間",
    prompt: "共同担保目録の保存期間は？",
    choices: ["永久", "30年", "20年", "10年", "5年"],
    correctChoice: "10年",
    explanation: "共同担保目録は、全ての事項を抹消した日から10年間保存される。",
    source: storagePeriodSource,
    tags: ["共同担保目録"],
  },
  {
    id: "storage-trust-register",
    category: "保存期間",
    prompt: "信託目録の保存期間は？",
    choices: ["永久", "30年", "20年", "10年", "5年"],
    correctChoice: "20年",
    explanation: "信託目録は、信託の登記を抹消した日から20年間保存される。",
    source: storagePeriodSource,
    tags: ["信託目録"],
  },
  {
    id: "storage-reception-book",
    category: "保存期間",
    prompt: "受付帳に記録された情報の保存期間は？",
    choices: ["永久", "30年", "20年", "10年", "1年"],
    correctChoice: "10年",
    explanation:
      "受付帳に記録された情報は、受付の年の翌年から10年間保存される。ただし、登記識別情報に関する証明の請求に係る受付帳は別である。",
    source: storagePeriodSource,
    tags: ["受付帳"],
  },
  {
    id: "storage-registration-identification-certificate-reception-book",
    category: "保存期間",
    prompt: "登記識別情報に関する証明の請求に係る受付帳の情報の保存期間は？",
    choices: ["永久", "10年", "5年", "3年", "1年"],
    correctChoice: "1年",
    explanation:
      "登記識別情報に関する証明の請求に係る受付帳の情報は、受付の年の翌年から1年間保存される。",
    source: storagePeriodSource,
    tags: ["受付帳", "登記識別情報", "証明の請求"],
  },
  {
    id: "storage-registration-identification-invalidation-request",
    category: "保存期間",
    prompt: "登記識別情報の失効の申出に関する情報の保存期間は？",
    choices: ["永久", "30年", "20年", "10年", "5年"],
    correctChoice: "10年",
    explanation: "登記識別情報の失効の申出に関する情報は、申出の受付の日から10年間保存される。",
    source: storagePeriodSource,
    tags: ["登記識別情報", "失効の申出"],
  },
  {
    id: "storage-request-documents",
    category: "保存期間",
    prompt:
      "登記事項証明書の交付請求書など、請求書類つづり込み帳の書類に記載された情報の保存期間は？",
    choices: ["永久", "10年", "5年", "3年", "1年"],
    correctChoice: "1年",
    explanation: "請求書類つづり込み帳の書類に記載された情報は、受付の日から1年間保存される。",
    source: storagePeriodSource,
    tags: ["登記事項証明書", "交付請求", "請求書類つづり込み帳"],
  },
  {
    id: "storage-legal-inheritance-information-list-file",
    category: "保存期間",
    prompt: "法定相続情報一覧図つづり込み帳の保存期間は？",
    choices: ["作成の年の翌年から1年", "作成の年の翌年から3年", "作成の年の翌年から5年", "作成の年の翌年から10年", "永久"],
    correctChoice: "作成の年の翌年から5年",
    explanation:
      "法定相続情報一覧図つづり込み帳には、法定相続情報一覧図とその保管の申出に関する書類がつづり込まれ、作成の年の翌年から5年間保存される。法務局の案内では、一覧図は申出日の翌年から起算して5年間保存され、その間は当初の申出人が写しの再交付を受けられる。",
    source: "不動産登記規則第27条の9・第28条第2項第6号（2026年8月25日確認）",
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 2,
    tags: ["法定相続情報一覧図", "法定相続情報一覧図つづり込み帳", "再交付"],
  },
  {
    id: "registration-identification-electronic-unreceived",
    sets: ["real-estate-registration"],
    category: "不動産登記法・登記識別情報",
    prompt:
      "電子情報処理組織を使用して登記識別情報の通知を受ける場合、いつまでに自己の電子計算機のファイルへ記録しないと、通知を要しない場合に当たる？",
    choices: ["7日以内", "14日以内", "30日以内", "2か月以内", "3か月以内"],
    correctChoice: "30日以内",
    explanation:
      "登記識別情報が登記官のファイルに記録され、送信可能になった時から30日以内に、通知を受けるべき者が自己の電子計算機のファイルへ記録しない場合である。単に申請日や登記完了日から30日ではない点に注意する。",
    source: `不動産登記規則第64条第1項第2号（${realEstateRegistrationConfirmedAt}）`,
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 2,
    tags: ["登記識別情報", "電子申請", "通知を要しない場合"],
  },
  {
    id: "registration-identification-paper-unreceived",
    sets: ["real-estate-registration"],
    category: "不動産登記法・登記識別情報",
    prompt:
      "書面で登記識別情報の通知を受ける場合、いつまでに登記識別情報通知書を受領しないと、通知を要しない場合に当たる？",
    choices: ["30日以内", "2か月以内", "3か月以内", "6か月以内", "1年以内"],
    correctChoice: "3か月以内",
    explanation:
      "通知を受けるべき者が、登記完了の時から3か月以内に登記識別情報を記載した書面を受領しない場合である。起算点は申請日ではなく登記完了時となる。",
    source: `不動産登記規則第64条第1項第3号（${realEstateRegistrationConfirmedAt}）`,
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 2,
    tags: ["登記識別情報", "書面申請", "通知を要しない場合"],
  },
  {
    id: "registration-electronic-attachment-paper-deadline",
    sets: ["real-estate-registration"],
    category: "不動産登記法・申請手続",
    prompt:
      "電子申請で、特例により添付情報を記載した書面を提出する場合、その書面を登記所へ提出する期限は？",
    choices: ["受付の日から2日以内", "受付の日から3日以内", "受付の日から7日以内", "受付の日から14日以内", "受付の日から30日以内"],
    correctChoice: "受付の日から2日以内",
    explanation:
      "電子申請で添付情報を別途書面により提供する場合、当該書面は申請の受付の日から2日以内に提出する。送付する場合は、引受けと配達の記録が残る書留郵便等による。",
    source: `不動産登記規則第21条第2項・第4項（${realEstateRegistrationConfirmedAt}）`,
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 2,
    tags: ["電子申請", "添付情報", "添付書面", "特例"],
  },
  {
    id: "registration-tax-reuse-after-withdrawal",
    sets: ["real-estate-registration"],
    category: "不動産登記法・登録免許税",
    prompt:
      "取下げに伴い再使用証明を受けた登録免許税の領収証書・収入印紙を、同じ登記官署等で再使用できる期限は？",
    choices: ["取下げの日から3か月以内", "取下げの日から6か月以内", "取下げの日から1年以内", "証明の日から1年以内", "取下げの日から5年以内"],
    correctChoice: "取下げの日から1年以内",
    explanation:
      "申請の取下げと同時に再使用の申出をして証明を受けると、取下げの日から1年以内に同じ登記官署等で再使用できる。再使用証明を受けた場合、その登録免許税は原則として還付されない。再使用しないこととなった場合の還付申出期限は、証明の日から1年を経過する日までであり、別の期間である。",
    source: `登録免許税法第31条第3項・第5項（${realEstateRegistrationConfirmedAt}）`,
    sourceUrl: registrationAndLicenseTaxActUrl,
    importance: 2,
    tags: ["登録免許税", "申請の取下げ", "再使用証明", "還付"],
  },
  {
    id: "registration-prior-notice-domestic",
    sets: ["real-estate-registration"],
    category: "不動産登記法・事前通知",
    prompt:
      "登記識別情報を提供できず事前通知を受けた登記義務者が国内に住所を有する場合、申請が真実である旨を申し出る期間は？",
    choices: ["通知発送日から1週間", "通知発送日から2週間", "通知受領日から2週間", "申請受付日から2週間", "通知発送日から4週間"],
    correctChoice: "通知発送日から2週間",
    explanation:
      "国内に住所を有する登記義務者の申出期間は、事前通知を発送した日から2週間である。通知を受け取った日ではなく、発送日が起算点となる。",
    source: `不動産登記法第23条第1項・不動産登記規則第70条第8項（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 3,
    tags: ["事前通知", "登記識別情報", "国内住所", "申出期間"],
  },
  {
    id: "registration-prior-notice-foreign",
    sets: ["real-estate-registration"],
    category: "不動産登記法・事前通知",
    prompt:
      "登記識別情報を提供できず事前通知を受けた登記義務者が外国に住所を有する場合、申請が真実である旨を申し出る期間は？",
    choices: ["通知発送日から2週間", "通知受領日から2週間", "通知発送日から3週間", "通知発送日から4週間", "通知受領日から4週間"],
    correctChoice: "通知発送日から4週間",
    explanation:
      "登記義務者が外国に住所を有する場合の申出期間は、事前通知を発送した日から4週間である。国内住所の場合の2週間と対比して覚える。",
    source: `不動産登記法第23条第1項・不動産登記規則第70条第8項ただし書（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 3,
    tags: ["事前通知", "登記識別情報", "外国住所", "申出期間"],
  },
  {
    id: "registration-inheritance-basic-obligation",
    sets: ["real-estate-registration"],
    category: "不動産登記法・相続登記",
    prompt: "相続により不動産の所有権を取得した者が、相続登記を申請しなければならない期限は？",
    choices: ["相続開始を知った日から1年以内", "相続開始を知った日から3年以内", "所有権取得を知った日から3年以内", "相続開始と所有権取得を知った日から3年以内", "相続開始の日から10年以内"],
    correctChoice: "相続開始と所有権取得を知った日から3年以内",
    explanation:
      "自己のために相続の開始があったことを知り、かつ、その不動産の所有権を取得したことを知った日から3年以内に申請する。相続人に対する遺贈で所有権を取得した者も同様である。",
    source: `不動産登記法第76条の2第1項（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: realEstateRegistrationActUrl,
    importance: 3,
    tags: ["相続登記", "申請義務", "遺贈", "所有権移転登記"],
  },
  {
    id: "registration-inheritance-partition-obligation",
    sets: ["real-estate-registration"],
    category: "不動産登記法・相続登記",
    prompt:
      "法定相続分による相続登記後、遺産分割により法定相続分を超える所有権を取得した者が、その結果に基づく登記を申請する期限は？",
    choices: ["相続開始の日から3年以内", "相続登記の日から3年以内", "遺産分割の日から1年以内", "遺産分割の日から3年以内", "遺産分割の日から10年以内"],
    correctChoice: "遺産分割の日から3年以内",
    explanation:
      "法定相続分による相続登記後に遺産分割が成立した場合は、遺産分割の日から3年以内に、その結果を反映する所有権移転登記を申請する。相続人申告登記後に遺産分割で所有権を取得した場合も、同じく遺産分割の日から3年以内である。",
    source: `不動産登記法第76条の2第2項・第76条の3第4項（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: realEstateRegistrationActUrl,
    importance: 3,
    tags: ["相続登記", "遺産分割", "相続人申告登記", "申請義務"],
  },
  {
    id: "registration-owner-address-name-change-obligation",
    sets: ["real-estate-registration"],
    category: "不動産登記法・住所等変更",
    prompt: "所有権の登記名義人の氏名・名称・住所に変更があった場合、変更登記を申請する期限は？",
    choices: ["変更の日から1年以内", "変更の日から2年以内", "変更を知った日から2年以内", "変更の日から3年以内", "次の登記申請まで"],
    correctChoice: "変更の日から2年以内",
    explanation:
      "所有権の登記名義人は、住所等の変更があった日から2年以内に変更登記を申請する。2026年4月1日より前の変更で未登記のものも対象となり、原則として2028年3月31日までに申請する必要がある。",
    source: `不動産登記法第76条の5・民法等の一部を改正する法律附則第5条第7項（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: addressChangeRegistrationGuideUrl,
    importance: 3,
    tags: ["住所等変更登記", "氏名変更", "住所変更", "申請義務"],
  },
  {
    id: "registration-attached-seal-certificate-age",
    sets: ["real-estate-registration"],
    category: "不動産登記法・添付情報",
    prompt:
      "不動産登記令第16条第2項または第18条第2項により書面へ添付する印鑑証明書は、原則として作成後どの期間内のものが必要？",
    choices: ["1か月以内", "3か月以内", "6か月以内", "1年以内", "期間制限なし"],
    correctChoice: "3か月以内",
    explanation:
      "申請情報を記載した書面や代理権限を証する書面に押印した印鑑について、同令の規定により添付する証明書は、作成後3か月以内のものでなければならない。官庁・公署による嘱託など、添付自体を要しない場合がある。",
    source: `不動産登記令第16条第2項・第3項、第18条第2項・第3項（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: realEstateRegistrationOrderUrl,
    importance: 2,
    tags: ["印鑑証明書", "書面申請", "代理権限証明情報", "添付情報"],
  },
  {
    id: "registration-representative-qualification-document-age",
    sets: ["real-estate-registration"],
    category: "不動産登記法・添付情報",
    prompt:
      "法人の代表者等の資格を証する情報として、公務員が職務上作成した書面を提供する場合、原則として作成後どの期間内のものが必要？",
    choices: ["1か月以内", "3か月以内", "6か月以内", "1年以内", "期間制限なし"],
    correctChoice: "3か月以内",
    explanation:
      "不動産登記令第7条第1項第1号ロまたは第2号の情報を記載した公務員作成の書面は、作成後3か月以内のものに限られる。会社法人等番号を提供して資格証明情報を省略できる場合などがある。",
    source: `不動産登記令第17条（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: realEstateRegistrationOrderUrl,
    importance: 2,
    tags: ["資格証明情報", "代表者", "法人", "添付情報"],
  },
  {
    id: "registration-tax-refund-after-unused-reuse-certificate",
    sets: ["real-estate-registration"],
    category: "不動産登記法・登録免許税",
    prompt:
      "再使用証明を受けた登録免許税の領収証書・収入印紙を再使用しないこととなった場合、還付を申し出られる期限は？",
    choices: ["取下げの日から6か月を経過する日まで", "取下げの日から1年を経過する日まで", "証明の日から6か月を経過する日まで", "証明の日から1年を経過する日まで", "証明の日から5年を経過する日まで"],
    correctChoice: "証明の日から1年を経過する日まで",
    explanation:
      "再使用しないこととなったときは、再使用証明をした登記機関に対し、証明の日から1年を経過する日までに、証明の無効化と登録免許税の還付を申し出ることができる。再使用期限の起算点は取下げの日、還付申出期限の起算点は証明の日である。",
    source: `登録免許税法第31条第5項（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: registrationAndLicenseTaxActUrl,
    importance: 2,
    tags: ["登録免許税", "再使用証明", "還付", "申出期限"],
  },
  {
    id: "registration-tax-electronic-payment-no-application",
    sets: ["real-estate-registration"],
    category: "不動産登記法・登録免許税",
    prompt:
      "電子的な方法で登録免許税を納付した後、登記等を受けることをやめた場合、還付に必要な税務署長への通知を請求できる期限は？",
    choices: ["納付の日から30日を経過する日まで", "納付の日から3か月を経過する日まで", "納付の日から6か月を経過する日まで", "申請予定日から6か月を経過する日まで", "納付の日から1年を経過する日まで"],
    correctChoice: "納付の日から6か月を経過する日まで",
    explanation:
      "原則として納付の日から6か月を経過する日までに、登記機関へ申し出て税務署長への通知を請求する。納付委託の場合は委託の日が起算点となる。申請をしないまま6か月を経過した場合は、この請求があったものとみなされる。",
    source: `登録免許税法第31条第6項・第7項（${realEstateRegistrationDeadlinesConfirmedAt}）`,
    sourceUrl: registrationAndLicenseTaxActUrl,
    importance: 2,
    tags: ["登録免許税", "電子納付", "還付", "通知請求"],
  },
];

const civilCodeUrl = "https://laws.e-gov.go.jp/law/129AC0000000089";
const landAndHouseLeaseActUrl = "https://laws.e-gov.go.jp/law/403AC0000000090";
const confirmedAt = "2026年8月13日確認";

const civilLawQuestions: Question[] = [
  {
    id: "civil-absence-ordinary",
    sets: ["civil-law"],
    category: "民法・総則",
    prompt: "普通失踪で、失踪宣告の要件となる生死不明の期間は？",
    choices: ["1年", "3年", "5年", "7年", "10年"],
    correctChoice: "7年",
    explanation: "不在者の生死が7年間明らかでないとき、家庭裁判所は利害関係人の請求により失踪の宣告をすることができる。",
    source: `民法第30条第1項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["失踪宣告", "普通失踪"],
  },
  {
    id: "civil-absence-special",
    sets: ["civil-law"],
    category: "民法・総則",
    prompt: "特別失踪で、危難が去った後に生死不明が続く必要期間は？",
    choices: ["6か月", "1年", "3年", "5年", "7年"],
    correctChoice: "1年",
    explanation: "戦争・船舶の沈没その他の危難が去った後、1年間生死が明らかでないことが要件となる。死亡したものとみなされる時点は、危難が去った時である。",
    source: `民法第30条第2項・第31条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["失踪宣告", "特別失踪"],
  },
  {
    id: "civil-rescission-subjective",
    sets: ["civil-law"],
    category: "民法・総則",
    prompt: "取消権は、追認できる時から何年間行使しないと時効で消滅する？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "取消権は、追認をすることができる時から5年間行使しないと、時効によって消滅する。",
    source: `民法第126条前段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["取消権", "消滅時効"],
  },
  {
    id: "civil-rescission-objective",
    sets: ["civil-law"],
    category: "民法・総則",
    prompt: "取消権は、行為の時から何年を経過すると消滅する？",
    choices: ["5年", "10年", "15年", "20年", "30年"],
    correctChoice: "20年",
    explanation: "追認できる時からの5年とは別に、行為の時から20年を経過したときも取消権は消滅する。",
    source: `民法第126条後段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["取消権", "消滅時効"],
  },
  {
    id: "civil-acquisitive-prescription-good-faith",
    sets: ["civil-law"],
    category: "民法・物権",
    prompt: "所有の意思をもって平穏・公然に占有し、占有開始時に善意無過失だった場合、所有権の取得時効期間は？",
    choices: ["5年", "7年", "10年", "15年", "20年"],
    correctChoice: "10年",
    explanation: "占有開始時に善意かつ無過失であれば、10年間の占有で所有権を時効取得する。",
    source: `民法第162条第2項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["取得時効", "善意無過失"],
  },
  {
    id: "civil-acquisitive-prescription-general",
    sets: ["civil-law"],
    category: "民法・物権",
    prompt: "善意無過失の短期取得時効が成立しない場合、所有権の取得時効期間は？",
    choices: ["5年", "10年", "15年", "20年", "30年"],
    correctChoice: "20年",
    explanation: "所有の意思をもって平穏・公然に他人の物を20年間占有すると、所有権を取得する。",
    source: `民法第162条第1項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["取得時効"],
  },
  {
    id: "civil-lease-maximum",
    sets: ["civil-law"],
    category: "民法・契約",
    prompt: "民法上の賃貸借について、1回に定められる存続期間の上限は？",
    choices: ["10年", "20年", "30年", "50年", "上限なし"],
    correctChoice: "50年",
    explanation: "賃貸借の存続期間は50年を超えられない。更新はできるが、更新後の期間も更新時から50年を超えられない。",
    source: `民法第604条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["賃貸借", "存続期間"],
  },
  {
    id: "civil-land-lease-minimum",
    sets: ["civil-law"],
    category: "民法・契約",
    prompt: "借地借家法上の普通借地権について、当初の存続期間は原則何年？",
    choices: ["10年", "20年", "30年", "50年", "上限なし"],
    correctChoice: "30年",
    explanation: "普通借地権の当初の存続期間は30年。契約で30年より長い期間を定めたときは、その期間となる。",
    source: `借地借家法第3条（${confirmedAt}）`,
    sourceUrl: landAndHouseLeaseActUrl,
    importance: 2,
    tags: ["借地権", "存続期間"],
  },
  {
    id: "civil-superficies-ground-rent-default",
    sets: ["civil-law"],
    category: "民法・物権",
    prompt: "定期の地代を支払う地上権者が、何年以上続けて地代を支払わないと、土地所有者は地上権の消滅を請求できる？",
    choices: ["1年以上", "2年以上", "3年以上", "5年以上", "10年以上"],
    correctChoice: "2年以上",
    explanation: "地上権の地代には永小作権の規定が準用され、引き続き2年以上支払を怠ると、土地所有者は消滅を請求できる。",
    source: `民法第266条第1項・第276条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["地上権", "地代", "消滅請求"],
  },
  {
    id: "civil-easement-extinctive-prescription",
    sets: ["civil-law"],
    category: "民法・物権",
    prompt: "地役権の消滅時効期間は？",
    choices: ["5年", "10年", "15年", "20年", "30年"],
    correctChoice: "20年",
    explanation: "地役権は所有権以外の財産権として20年で時効消滅する。起算点は、非継続地役権では最後の行使時、継続地役権では行使を妨げる事実が生じた時である。",
    source: `民法第166条第2項・第291条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["地役権", "消滅時効"],
  },
  {
    id: "civil-immovable-pledge-duration",
    sets: ["civil-law"],
    category: "民法・物権",
    prompt: "不動産質権の1回の存続期間の上限は？",
    choices: ["5年", "10年", "20年", "30年", "50年"],
    correctChoice: "10年",
    explanation: "不動産質権の存続期間は10年を超えられない。更新できるが、更新後も更新時から10年が上限となる。",
    source: `民法第360条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["不動産質権", "存続期間"],
  },
  {
    id: "civil-prescription-court-claim",
    sets: ["civil-law"],
    category: "民法・時効",
    prompt: "裁判上の請求が、権利を確定させずに終了した場合、その終了時から時効完成が猶予される期間は？",
    choices: ["3か月", "6か月", "1年", "3年", "5年"],
    correctChoice: "6か月",
    explanation: "裁判上の請求などが権利を確定させずに終了した場合、終了時から6か月を経過するまで時効は完成しない。",
    source: `民法第147条第1項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["時効完成猶予", "裁判上の請求"],
  },
  {
    id: "civil-prescription-provisional-seizure",
    sets: ["civil-law"],
    category: "民法・時効",
    prompt: "仮差押え・仮処分の事由が終了した後、時効完成が猶予される期間は？",
    choices: ["3か月", "6か月", "1年", "3年", "5年"],
    correctChoice: "6か月",
    explanation: "仮差押えまたは仮処分の事由が終了した時から6か月を経過するまで、時効は完成しない。",
    source: `民法第149条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["時効完成猶予", "仮差押え", "仮処分"],
  },
  {
    id: "civil-prescription-demand",
    sets: ["civil-law"],
    category: "民法・時効",
    prompt: "催告があった時から、時効完成が猶予される期間は？",
    choices: ["3か月", "6か月", "1年", "3年", "5年"],
    correctChoice: "6か月",
    explanation: "催告時から6か月を経過するまで時効は完成しない。この猶予中に再度催告しても、完成猶予の効力はない。",
    source: `民法第150条（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["時効完成猶予", "催告"],
  },
  {
    id: "civil-claim-prescription-subjective",
    sets: ["civil-law"],
    category: "民法・時効",
    prompt: "債権者が権利を行使できることを知った時から、債権の消滅時効期間は？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "債権者が権利を行使できることを知った時から5年間行使しないと、債権は時効によって消滅する。",
    source: `民法第166条第1項第1号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["債権", "消滅時効"],
  },
  {
    id: "civil-claim-prescription-objective",
    sets: ["civil-law"],
    category: "民法・時効",
    prompt: "権利を行使できる時から、債権の消滅時効期間は？",
    choices: ["3年", "5年", "10年", "20年", "30年"],
    correctChoice: "10年",
    explanation: "権利を行使できる時から10年間行使しないと、債権は時効によって消滅する。知った時からの5年と、先に満了する方で完成する。",
    source: `民法第166条第1項第2号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["債権", "消滅時効"],
  },
  {
    id: "civil-inheritance-recovery-subjective",
    sets: ["civil-law"],
    category: "民法・相続",
    prompt: "相続権を侵害された事実を知った時から、相続回復請求権の消滅時効期間は？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "相続人または法定代理人が相続権を侵害された事実を知った時から5年間行使しないと、時効で消滅する。",
    source: `民法第884条前段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["相続回復請求権", "消滅時効"],
  },
  {
    id: "civil-inheritance-recovery-objective",
    sets: ["civil-law"],
    category: "民法・相続",
    prompt: "相続開始の時から、相続回復請求権が消滅するまでの期間は？",
    choices: ["5年", "10年", "15年", "20年", "30年"],
    correctChoice: "20年",
    explanation: "相続開始の時から20年を経過したときも、相続回復請求権は消滅する。",
    source: `民法第884条後段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["相続回復請求権"],
  },
  {
    id: "civil-legitime-subjective",
    sets: ["civil-law"],
    category: "民法・相続",
    prompt: "相続開始と遺留分を侵害する贈与・遺贈を知った時から、遺留分侵害額請求権の消滅時効期間は？",
    choices: ["6か月", "1年", "3年", "5年", "10年"],
    correctChoice: "1年",
    explanation: "相続開始と遺留分侵害の贈与・遺贈を知った時から1年間行使しないと、時効で消滅する。",
    source: `民法第1048条前段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 2,
    tags: ["遺留分侵害額請求権", "消滅時効"],
  },
  {
    id: "civil-legitime-objective",
    sets: ["civil-law"],
    category: "民法・相続",
    prompt: "相続開始の時から、遺留分侵害額請求権が消滅するまでの期間は？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "10年",
    explanation: "相続開始の時から10年を経過したときも、遺留分侵害額請求権は消滅する。",
    source: `民法第1048条後段（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["遺留分侵害額請求権"],
  },
  {
    id: "civil-repurchase-maximum",
    sets: ["civil-law"],
    category: "民法・契約",
    prompt: "買戻しの期間として特約で定められる上限は？",
    choices: ["3年", "5年", "10年", "20年", "50年"],
    correctChoice: "10年",
    explanation: "買戻しの期間は10年を超えられず、これより長く定めても10年となる。いったん定めた期間は後から伸長できない。",
    source: `民法第580条第1項・第2項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["買戻し", "買戻特約"],
  },
  {
    id: "civil-repurchase-unspecified",
    sets: ["civil-law"],
    category: "民法・契約",
    prompt: "買戻しについて期間を定めなかった場合、何年以内に買戻しをしなければならない？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "買戻しについて期間を定めなかったときは、5年以内に買戻しをしなければならない。",
    source: `民法第580条第3項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["買戻し", "買戻特約"],
  },
  {
    id: "civil-short-lease-forest",
    sets: ["civil-law"],
    category: "民法・契約",
    prompt: "処分権限のない者がする、樹木の栽植・伐採を目的とする山林の短期賃貸借の上限は？",
    choices: ["3年", "5年", "10年", "20年", "50年"],
    correctChoice: "10年",
    explanation: "処分権限のない者による山林の賃貸借は10年を超えられない。",
    source: `民法第602条第1号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["短期賃貸借", "山林"],
  },
  {
    id: "civil-short-lease-land",
    sets: ["civil-law"],
    category: "民法・契約",
    prompt: "処分権限のない者がする、山林以外の土地の短期賃貸借の上限は？",
    choices: ["1年", "3年", "5年", "10年", "20年"],
    correctChoice: "5年",
    explanation: "樹木の栽植・伐採を目的とする山林以外の土地の賃貸借は、5年を超えられない。",
    source: `民法第602条第2号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["短期賃貸借", "土地"],
  },
  {
    id: "civil-short-lease-building",
    sets: ["civil-law"],
    category: "民法・契約",
    prompt: "処分権限のない者がする、建物の短期賃貸借の上限は？",
    choices: ["1年", "2年", "3年", "5年", "10年"],
    correctChoice: "3年",
    explanation: "処分権限のない者による建物の賃貸借は、3年を超えられない。",
    source: `民法第602条第3号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["短期賃貸借", "建物"],
  },
  {
    id: "civil-short-lease-movables",
    sets: ["civil-law"],
    category: "民法・契約",
    prompt: "処分権限のない者がする、動産の短期賃貸借の上限は？",
    choices: ["3か月", "6か月", "1年", "3年", "5年"],
    correctChoice: "6か月",
    explanation: "処分権限のない者による動産の賃貸借は、6か月を超えられない。",
    source: `民法第602条第4号（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 1,
    tags: ["短期賃貸借", "動産"],
  },
  {
    id: "civil-inheritance-deliberation",
    sets: ["civil-law"],
    category: "民法・相続",
    prompt: "相続人が自己のために相続開始があったことを知った時から、承認・放棄を決める熟慮期間は？",
    choices: ["1か月", "3か月", "6か月", "1年", "3年"],
    correctChoice: "3か月",
    explanation: "原則として3か月以内に単純承認・限定承認または放棄をしなければならない。家庭裁判所は請求により期間を伸長できる。",
    source: `民法第915条第1項（${confirmedAt}）`,
    sourceUrl: civilCodeUrl,
    importance: 3,
    tags: ["相続の承認", "相続放棄", "熟慮期間"],
  },
];

questions.push(...civilLawQuestions);

const boundaryDeterminationQuestions: Question[] = [
  {
    id: "boundary-determination-record",
    sets: ["storage", "boundary-determination"],
    category: "筆界特定・保存期間",
    prompt: "筆界特定書に記載され、又は記録された情報の保存期間は？",
    choices: ["永久", "作成の年の翌年から30年", "送付を受けた年の翌年から30年", "閉鎖後30年", "10年"],
    correctChoice: "永久",
    explanation: "筆界特定書に記載され、又は記録された情報は、永久に保存される。筆界特定書以外の手続記録は30年であり、区別が重要である。",
    source: "不動産登記規則第235条第1項第1号（2026年9月24日確認）",
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 3,
    tags: ["筆界特定書", "保存期間"],
  },
  {
    id: "boundary-determination-other-procedure-record",
    sets: ["storage", "boundary-determination"],
    category: "筆界特定・保存期間",
    prompt: "筆界特定書以外の筆界特定手続記録に記載され、又は記録された情報の保存期間は？",
    choices: ["受付の日から30年", "作成の年の翌年から30年", "送付を受けた年の翌年から30年", "閉鎖後30年", "永久"],
    correctChoice: "送付を受けた年の翌年から30年",
    explanation: "対象土地の所在地を管轄する登記所が、規則233条により筆界特定手続記録の送付を受けた年の翌年から30年間保存する。申請の受付日や筆界特定日が起算点ではない。",
    source: "不動産登記規則第235条第1項第2号（2026年9月24日確認）",
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 3,
    tags: ["筆界特定手続記録", "保存期間", "起算点"],
  },
  {
    id: "boundary-determination-ledgers",
    sets: ["storage", "boundary-determination"],
    category: "筆界特定・保存期間",
    prompt: "筆界特定受付等記録簿及び筆界特定関係簿の保存期間は？",
    choices: ["受付の日から30年", "作成の年の翌年から30年", "送付を受けた年の翌年から30年", "作成の日から10年", "永久"],
    correctChoice: "作成の年の翌年から30年",
    explanation: "筆界特定受付等記録簿及び筆界特定関係簿は、作成の年の翌年から30年間保存する。筆界特定書以外の手続記録の起算点とは異なる。",
    source: "不動産登記規則第235条の2第1号（2026年9月24日確認）",
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 2,
    tags: ["筆界特定受付等記録簿", "筆界特定関係簿", "保存期間"],
  },
  {
    id: "boundary-determination-diaries",
    sets: ["storage", "boundary-determination"],
    category: "筆界特定・保存期間",
    prompt: "筆界特定事務日記帳及び筆界特定関係事務日記帳の保存期間は？",
    choices: ["作成の年の翌年から1年", "作成の年の翌年から3年", "作成の年の翌年から5年", "作成の年の翌年から10年", "作成の年の翌年から30年"],
    correctChoice: "作成の年の翌年から3年",
    explanation: "両事務日記帳は、作成の年の翌年から3年間保存する。受付等記録簿・関係簿の30年と混同しない。",
    source: "不動産登記規則第235条の2第2号（2026年9月24日確認）",
    sourceUrl: realEstateRegistrationRulesUrl,
    importance: 1,
    tags: ["筆界特定事務日記帳", "筆界特定関係事務日記帳", "保存期間"],
  },
  {
    id: "boundary-determination-unknown-party-notice",
    sets: ["boundary-determination"],
    category: "筆界特定・通知",
    prompt: "所在不明の関係人に対し公告・掲示等の措置で筆界特定申請の通知をした場合、いつ通知が到達したものとみなされる？",
    choices: ["措置を開始した日", "措置を開始した日から1週間を経過したとき", "措置を開始した日から2週間を経過したとき", "公告の日から30日を経過したとき", "筆界特定の日"],
    correctChoice: "措置を開始した日から2週間を経過したとき",
    explanation: "関係人の所在が判明しないときは、法定の閲覧可能措置と掲示等で通知できる。この措置を開始した日から2週間を経過したときに到達擬制が生じる。筆界特定後の通知にも準用される。",
    source: "不動産登記法第133条第2項・第144条第2項（2026年9月24日確認）",
    sourceUrl: realEstateRegistrationActUrl,
    importance: 2,
    tags: ["筆界特定", "所在不明", "通知", "到達擬制"],
  },
];

const surveyorLawQuestions: Question[] = [
  {
    id: "surveyor-law-registration-cancellation-no-practice",
    sets: ["surveyor-law"],
    category: "土地家屋調査士法・登録",
    prompt: "調査士が引き続き業務を行わないことを理由に、調査士会連合会が登録を取り消すことができるのは、どの期間を経過したとき？",
    choices: ["6か月", "1年", "2年", "3年", "5年"],
    correctChoice: "2年",
    explanation: "引き続き2年以上業務を行わないとき、調査士会連合会は登録を取り消すことができる。法15条の当然取消しではなく、法16条1項1号による『できる』取消しである。",
    source: "土地家屋調査士法第16条第1項第1号（2026年9月24日確認）",
    sourceUrl: surveyorActUrl,
    importance: 2,
    tags: ["登録取消し", "業務を行わない", "任意的取消し"],
  },
  {
    id: "surveyor-law-registration-application-no-disposition",
    sets: ["surveyor-law"],
    category: "土地家屋調査士法・登録",
    prompt: "調査士名簿への登録を申請した日から、何か月を経過しても処分がないとき、申請者はどうできる？",
    choices: ["1か月後、登録されたものとして業務を開始できる", "3か月後、登録されたものとして業務を開始できる", "3か月後、登録を拒否されたものとして法務大臣に審査請求できる", "6か月後、法務局長に異議申立てできる", "1年後、当然に登録される"],
    correctChoice: "3か月後、登録を拒否されたものとして法務大臣に審査請求できる",
    explanation: "申請の日から3月を経過しても何らの処分がないときは、登録されたものとみなされるのではない。登録を拒否されたものとして、法務大臣に審査請求できる。",
    source: "土地家屋調査士法第12条第2項（2026年9月24日確認）",
    sourceUrl: surveyorActUrl,
    importance: 3,
    tags: ["登録申請", "不作為", "審査請求"],
  },
  {
    id: "surveyor-law-business-suspension",
    sets: ["surveyor-law"],
    category: "土地家屋調査士法・懲戒",
    prompt: "法務大臣が、調査士又は調査士法人に命じることができる業務停止の最長期間は？",
    choices: ["6か月以内", "1年以内", "2年以内", "3年以内", "5年以内"],
    correctChoice: "2年以内",
    explanation: "調査士は2年以内の業務停止、調査士法人は2年以内の業務の全部又は一部の停止を命じられ得る。いずれも最長は2年である。",
    source: "土地家屋調査士法第42条第2号・第43条第1項第2号（2026年9月24日確認）",
    sourceUrl: surveyorActUrl,
    importance: 2,
    tags: ["懲戒", "業務停止", "調査士法人"],
  },
  {
    id: "surveyor-law-business-prohibition-disqualification",
    sets: ["surveyor-law"],
    category: "土地家屋調査士法・欠格事由",
    prompt: "土地家屋調査士法42条により業務禁止の処分を受けた者が、再び調査士となる資格を有するまでの欠格期間は？",
    choices: ["処分の日から1年", "処分の日から2年", "処分の日から3年", "処分の日から5年", "処分の日から10年"],
    correctChoice: "処分の日から3年",
    explanation: "業務禁止処分を受けた日から3年を経過しない者は欠格者である。拘禁刑以上の刑、公務員の懲戒免職などにも3年の欠格事由がある。",
    source: "土地家屋調査士法第5条第5号（2026年9月24日確認）",
    sourceUrl: surveyorActUrl,
    importance: 2,
    tags: ["業務禁止", "欠格事由", "3年"],
  },
  {
    id: "surveyor-law-case-register",
    sets: ["storage", "surveyor-law"],
    category: "土地家屋調査士法・保存期間",
    prompt: "調査士の事件簿の保存期間は？",
    choices: ["作成の日から3年", "受託の日から5年", "閉鎖後5年", "閉鎖後7年", "永久"],
    correctChoice: "閉鎖後7年",
    explanation: "調査士の事件簿は、閉鎖後7年間保存しなければならない。作成日から3年の領収証副本とは、対象と起算点の両方が異なる。",
    source: "土地家屋調査士法施行規則第28条第2項（2026年9月24日確認）",
    sourceUrl: surveyorRulesUrl,
    importance: 3,
    tags: ["事件簿", "保存期間", "閉鎖後"],
  },
  {
    id: "surveyor-law-receipt-copy",
    sets: ["storage", "surveyor-law"],
    category: "土地家屋調査士法・保存期間",
    prompt: "調査士が依頼者から報酬を受けて作成する領収証の副本の保存期間は？",
    choices: ["作成の日から1年", "作成の日から3年", "作成の日から5年", "閉鎖後7年", "永久"],
    correctChoice: "作成の日から3年",
    explanation: "領収証の副本は、作成の日から3年間保存しなければならない。事件簿は閉鎖後7年であり、期間・起算点とも異なる。領収証は電磁的記録でも作成・保存できる。",
    source: "土地家屋調査士法施行規則第27条第1項・第2項（2026年9月24日確認）",
    sourceUrl: surveyorRulesUrl,
    importance: 2,
    tags: ["領収証", "副本", "保存期間"],
  },
];

questions.push(...boundaryDeterminationQuestions, ...surveyorLawQuestions);
